version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.14.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - test_data:/usr/share/elasticsearch/data/
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
      - network.host=localhost
      - bootstrap.memory_lock=true
    networks:
      - elk
    deploy:
      resources:
        limits:
          memory: 512M

  logstash:
    image: logstash:8.14.1
    container_name: logstash
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./elk-config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk-config/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ls_data:/usr/share/logstash/data
    environment:
      - http.host=0.0.0.0
      - xpack.monitoring.elasticsearch.hosts= [ "http://elasticsearch:9200" ]
      - xpack.monitoring.enabled=false
    networks:
      - elk
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 256M

  kibana:
    image: kibana:8.14.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - server.name= kibana
      - server.host= "0.0.0.0"
      - elasticsearch.hosts= [ "http://elasticsearch:9200" ]
      - monitoring.ui.container.elasticsearch.enabled= true
    volumes:
      - ./elk-config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - kb_data:/usr/share/kibana/data
    networks:
      - elk
    depends_on:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  elk:
    driver: bridge

volumes:
  test_data:
  ls_data:
  kb_data: