version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      # Database settings
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: pass
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HOSTNAME_DEBUG: true
      KC_HOSTNAME_STRICT_HTTPS: false

      # Admin credentials
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      # Optional: Specify a theme, hostname, or other settings
      KC_HOSTNAME: localhost
    ports:
      - "8080:8080"
    command:
      - start
      - --http-enabled=true
        - --optimized


  keycloak-az:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      # Database settings
      KC_DB: postgres
      KC_DB_URL: ${host}
      KC_DB_USERNAME: ${user}
      KC_DB_PASSWORD: ${pass}
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HOSTNAME_DEBUG: true
      KC_HOSTNAME_STRICT_HTTPS: false

      # Admin credentials
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      # Admin credentials
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Optional: Specify a theme, hostname, or other settings
      KC_HOSTNAME: ${localhost}
    ports:
      - "8080:8080"
    command:
      - start
      - --http-enabled=true
        - --optimized

