version: '3.8'
services:
  dots-mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --explicit_defaults_for_timestamp --event-scheduler=1
    deploy:
      resources:
        limits:
          memory: 512M
