version: '2'
services:
    mysql:
        extends:
            file: mysql.yml
            service: mysql
    kafka:
        extends:
            file: kafka.yml
            service: kafka
        environment:
            - KAFKA_ADVERTISED_HOST_NAME=kafka
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
    wiremock-helper:
      extends:
        file: wiremock.yml
        service: wiremock-helper
