version: '3.8'

services:
  wiremock-helper:
    image: ekino/wiremock:latest
    ports:
      - 8084:8080
    volumes:
      - ./resources/wiremock-helper/files:/wiremock/__files
      - ./resources/wiremock-helper/mappings:/wiremock/mappings
    entrypoint:
      - java
      - -jar
      - wiremock.jar
      - --verbose
    deploy:
      resources:
        limits:
          memory: 512M